################### 仿微信

#server:
#  port: 8080
#
#netty:
#  host: 127.0.0.1
#  port: 7397
#
#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp

# 定位模板的目录
#spring.mvc.view.prefix=classpath:/templates/
# 给返回的页面添加后缀名
#spring.mvc.view.suffix=.html



################### ES日志记录
## Server
#server:
#  port: 8080
#
### Netty
#netty:
#  host: 127.0.0.1
#  port: 7397
#
### Elasticsearch
#spring:
#  data:
#    elasticsearch:
#      cluster-name: SSSDNSY
#      cluster-nodes: 127.0.0.1:9300
#      repositories: true



################### 其他
## Server
#server:
#  port: 8899
#  context-path: /
#
### Spring
#spring:
#  mvc:
#    static-path-pattern: /static/**
#  freemarker:
#    settings:
#      number_format: 0.##########
#    template-loader-path: classpath:/templates/
#    suffix: .ftl
#    charset: UTF-8
#
#  #### rabbitmq
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#    # 手动提交消息
#    listener:
#      direct:
#        retry:
#          enabled: false
#          max-attempts: 3
#        acknowledge-mode: auto
#      simple:
#        retry:
#          enabled: false
#          max-attempts: 3
#        acknowledge-mode: auto
#
#
#
