## server
server:
  port: 8888

## spring
spring:
  application:
    name: one-stop-java
  data:
    ## redis
    redis:
      host: localhost
      port: 6379
  ## mysql
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&&useCursorFetch=true&&rewriteBatchedStatements=true
    username: root
    password: imi123
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## async excel
  excel:
    datasource:
      hikari:
        pool-name: excel
      url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&&useCursorFetch=true&&rewriteBatchedStatements=true
      username: root
      password: imi123
      driver-class-name: com.mysql.cj.jdbc.Driver
  ## jpa
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        boot:
          allow_jdbc_metadata_access: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never

## mybatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
