// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgInfo.proto

package netty.basic.demo12.domain;

public interface MsgBodyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:netty.basic.demo12.domain.MsgBody)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string channelId = 1;</code>
     *
     * @return The channelId.
     */
    String getChannelId();

    /**
     * <code>string channelId = 1;</code>
     *
     * @return The bytes for channelId.
     */
    com.google.protobuf.ByteString
    getChannelIdBytes();

    /**
     * <code>string msgInfo = 2;</code>
     *
     * @return The msgInfo.
     */
    String getMsgInfo();

    /**
     * <code>string msgInfo = 2;</code>
     *
     * @return The bytes for msgInfo.
     */
    com.google.protobuf.ByteString
    getMsgInfoBytes();
}
